# Increase the heap size for the Gradle daemon
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Enable parallel execution and build caching for better performance
org.gradle.parallel=true
org.gradle.caching=true

# Android-specific settings
android.useAndroidX=true
# Jetifier is often needed for older libraries, but can be disabled if not using them to speed up builds
android.enableJetifier=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.enableAppCompileTimeRClass=true
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=true
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=true
android.r8.optimizedResourceShrinking=true
android.builtInKotlin=true
android.newDsl=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
org.gradle.configuration-cache=true
